### ISSUE TITLE
[#104] 음악 실시간 스트리밍

### ISSUE THREAD

**Issue by doggydeok2** [boostcampwm-2021/WEB21-ShallWeSound#8]
사용자는 방장이 플레이하는 노래를 들을 수 있다
- **방 내 모든 사용자가 현재 실행된 음악을 동일 구간부터 청취한다.**
- 음악은 화면 상단의 뮤직 플레이어를 통해 실행된다.

**Comment by jsl0149** [comment]
- React video 태그는 public 경로안에 있는 것만 불러오는데 어떻게 불러올지

**Comment by jsl0149** [comment]
- 방 별 공유 스트리밍 기능 구현

**Comment by jsl0149** [comment]
- 방 별로 새로고침시 세션 유지 기능 필요
- 방에서 모든 사람이 나가면 방 삭제
-
